<?php
session_start();
error_reporting(E_ALL);
ini_set('display_errors', 1);
date_default_timezone_set('Asia/Colombo');

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../mongodb_config.php';

use Dompdf\Dompdf;

// ------------------ Check login ------------------
if (!isset($_SESSION['username']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../login.php");
    exit();
}

$username = $_SESSION['username'];

// ------------------ MongoDB collections ------------------
$usersCollection    = $db->users;
$productsCollection = $db->products;
$ordersCollection   = $db->orders;
$reportsCollection  = $db->reports;

// ------------------ Form Month & Year ------------------
// Convert month input to integer
$selectedMonth = isset($_POST['month']) ? (int)$_POST['month'] : (int)date('m');
$selectedYear  = isset($_POST['year']) ? (int)$_POST['year'] : (int)date('Y');

// Validate month range
if ($selectedMonth < 1 || $selectedMonth > 12) {
    $selectedMonth = (int)date('m');
}

// Convert month number to name
$monthName = date("F", mktime(0, 0, 0, $selectedMonth, 1));

// Initialize variables
$totalOrders = 0;
$totalQuantity = 0;
$totalIncome = 0;
$orders = [];
$pdfName = "";
$pdfGenerated = false;
$totalFarmers = $totalWholesalers = $totalDrivers = $totalProducts = 0;

// ------------------ Generate PDF if form is submitted ------------------
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['month'])) {
    
    // ------------------ Summary Data ------------------
    $totalFarmers     = $usersCollection->countDocuments(['role' => 'farmer']);
    $totalWholesalers = $usersCollection->countDocuments(['role' => 'wholesaler']);
    $totalDrivers     = $usersCollection->countDocuments(['role' => 'transporter']);
    $totalProducts    = $productsCollection->countDocuments([]);

    // ------------------ Date range for selected month ------------------
    $startDate = strtotime("first day of $monthName $selectedYear");
    $endDate   = strtotime("first day of next month $monthName $selectedYear");

    // Fix: Convert timestamps to milliseconds for MongoDB
    $startDateMs = $startDate * 1000;
    $endDateMs = $endDate * 1000;

    // Get orders for the selected month
    try {
        $ordersCursor = $ordersCollection->find([
            'order_date' => [
                '$gte' => new MongoDB\BSON\UTCDateTime($startDateMs),
                '$lt'  => new MongoDB\BSON\UTCDateTime($endDateMs)
            ]
        ]);
        
        $orders = iterator_to_array($ordersCursor);
        $totalOrders = count($orders);

        foreach ($orders as $order) {
            $totalQuantity += (int)($order['quantity'] ?? 0);
            $totalIncome  += (float)($order['total_amount'] ?? 0);
        }
    } catch (Exception $e) {
        error_log("Error fetching orders: " . $e->getMessage());
        $orders = [];
    }

    // ------------------ Build HTML for PDF ------------------
    $html = '<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Monthly Report - ' . $monthName . ' ' . $selectedYear . '</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h2 { text-align: center; color: #2c3e50; }
            .header-info { text-align: center; margin-bottom: 20px; }
            .section-title { background-color: #f2f2f2; padding: 10px; font-weight: bold; margin-top: 20px; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            th { background-color: #34495e; color: white; padding: 10px; text-align: left; }
            td { padding: 8px; border-bottom: 1px solid #ddd; }
            .total-row { font-weight: bold; background-color: #f9f9f9; }
        </style>
    </head>
    <body>';
    
    $html .= '<h2>ADMIN SYSTEM MONTHLY REPORT</h2>';
    $html .= '<div class="header-info">';
    $html .= '<p><strong>Month:</strong> ' . $monthName . ' &nbsp;&nbsp; <strong>Year:</strong> ' . $selectedYear . '</p>';
    $html .= '<p><strong>Generated On:</strong> ' . date('Y-m-d H:i:s') . '</p>';
    $html .= '<p><strong>Generated By:</strong> ' . $username . '</p>';
    $html .= '</div>';

    $html .= '<div class="section-title">System Summary</div>';
    $html .= '<table>';
    $html .= '<tr><td>Total Farmers:</td><td>' . $totalFarmers . '</td></tr>';
    $html .= '<tr><td>Total Wholesalers:</td><td>' . $totalWholesalers . '</td></tr>';
    $html .= '<tr><td>Total Drivers:</td><td>' . $totalDrivers . '</td></tr>';
    $html .= '<tr><td>Total Products:</td><td>' . $totalProducts . '</td></tr>';
    $html .= '<tr><td>Total Orders This Month:</td><td>' . $totalOrders . '</td></tr>';
    $html .= '<tr><td>Total Quantity Sold:</td><td>' . $totalQuantity . '</td></tr>';
    $html .= '<tr class="total-row"><td>Total Income (LKR):</td><td>' . number_format($totalIncome, 2) . '</td></tr>';
    $html .= '</table>';

    if ($totalOrders > 0) {
        $html .= '<div class="section-title">Orders List</div>';
        $html .= '<table>';
        $html .= '<tr>
                    <th>Order ID</th>
                    <th>Farmer</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Total Amount</th>
                    <th>Date</th>
                  </tr>';

        // Add each order row
        foreach ($orders as $order) {
            $productName = 'Unknown';
            if (!empty($order['product_id'])) {
                try {
                    // Convert to ObjectId if it's a string
                    $productId = $order['product_id'];
                    if (!($productId instanceof MongoDB\BSON\ObjectId) && is_string($productId)) {
                        $productId = new MongoDB\BSON\ObjectId($productId);
                    }
                    $pdoc = $productsCollection->findOne(['_id' => $productId]);
                    if ($pdoc && !empty($pdoc['name'])) {
                        $productName = $pdoc['name'];
                    }
                } catch (Exception $e) {
                    error_log("Error fetching product: " . $e->getMessage());
                }
            }

            $orderDate = '-';
            if (!empty($order['order_date'])) {
                try {
                    if ($order['order_date'] instanceof MongoDB\BSON\UTCDateTime) {
                        $dt = $order['order_date']->toDateTime();
                        $dt->setTimezone(new DateTimeZone('Asia/Colombo'));
                        $orderDate = $dt->format('Y-m-d H:i');
                    }
                } catch (Exception $e) {
                    error_log("Error parsing date: " . $e->getMessage());
                }
            }

            $html .= '<tr>
                        <td>' . substr((string)($order['_id'] ?? ''), -8) . '</td>
                        <td>' . htmlspecialchars($order['farmer'] ?? 'N/A') . '</td>
                        <td>' . htmlspecialchars($productName) . '</td>
                        <td>' . ($order['quantity'] ?? '0') . '</td>
                        <td>LKR ' . number_format($order['total_amount'] ?? 0, 2) . '</td>
                        <td>' . $orderDate . '</td>
                     </tr>';
        }

        $html .= '</table>';
    } else {
        $html .= '<p style="color: #666; font-style: italic; text-align: center;">No orders found for ' . $monthName . ' ' . $selectedYear . '</p>';
    }

    $html .= '</body></html>';

    // ------------------ Generate PDF ------------------
    $timestamp = time();
    $pdfName = "admin_report_" . $selectedYear . "_" . str_pad($selectedMonth, 2, '0', STR_PAD_LEFT) . "_" . $timestamp . ".pdf";
    $pdfPath = __DIR__ . "/$pdfName";

    try {
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        file_put_contents($pdfPath, $dompdf->output());
        
        // Save Report Metadata
        $reportsCollection->insertOne([
            'admin' => $username,
            'month' => $selectedMonth,
            'year' => $selectedYear,
            'month_name' => $monthName,
            'generated_at' => new MongoDB\BSON\UTCDateTime(),
            'file_name' => $pdfName,
            'total_farmers' => $totalFarmers,
            'total_wholesalers' => $totalWholesalers,
            'total_drivers' => $totalDrivers,
            'total_products' => $totalProducts,
            'total_orders' => $totalOrders,
            'total_quantity' => $totalQuantity,
            'total_income' => $totalIncome
        ]);
        
        $pdfGenerated = true;
        
    } catch (Exception $e) {
        error_log("Error generating PDF: " . $e->getMessage());
        $pdfGenerated = false;
    }
}

?>

<!DOCTYPE html>
<html>
<head>
    <title>Admin Monthly Report</title>
    <style>
        body { font-family: Arial, sans-serif; background: #f4f6f8; margin: 0; }
        .navbar { 
            background: linear-gradient(135deg, #141e30, #243b55); 
            padding: 14px 40px; 
            color: white; 
            display: flex; 
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }
        .nav-left h2 { margin: 0; color: white; }
        .nav-right a { 
            color: #eaeaea; 
            margin-left: 15px; 
            text-decoration: none; 
            padding: 8px 14px;
            border-radius: 4px;
            transition: background 0.3s;
        }
        .nav-right a.active { 
            background: #27ae60; 
            color: white; 
        }
        .nav-right a.logout { background: #e74c3c; color: white; }
        .nav-right a:hover { background: rgba(255,255,255,0.1); }
        
        h2 { text-align: center; margin: 20px 0; color: #2c3e50; }
        
        .form-box {
            width: 400px;
            margin: 30px auto;
            background: white;
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.08);
        }
        
        label { display: block; margin-bottom: 8px; font-weight: 600; color: #34495e; }
        
        select { 
            width: 100%; 
            padding: 12px 15px; 
            margin: 10px 0 20px; 
            border: 1px solid #ddd; 
            border-radius: 6px;
            font-size: 16px;
            box-sizing: border-box;
        }
        
        button { 
            width: 100%; 
            padding: 14px; 
            background: linear-gradient(135deg, #27ae60, #2ecc71); 
            color: white; 
            border: none; 
            border-radius: 6px; 
            font-size: 16px; 
            font-weight: 600; 
            cursor: pointer;
            transition: all 0.3s;
        }
        
        button:hover { 
            background: linear-gradient(135deg, #219653, #27ae60); 
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(39, 174, 96, 0.3);
        }
        
        iframe { 
            width: 90%; 
            height: 600px; 
            margin: 20px auto; 
            display: block;
            border: 1px solid #ddd; 
            border-radius: 8px;
            box-shadow: 0 3px 10px rgba(0,0,0,0.05);
        }
        
        .btn { 
            background: linear-gradient(135deg, #3498db, #2980b9); 
            color: white; 
            padding: 12px 25px; 
            text-decoration: none; 
            border-radius: 6px; 
            display: inline-block;
            margin: 20px auto;
            font-weight: 600;
            text-align: center;
            transition: all 0.3s;
        }
        
        .btn:hover { 
            background: linear-gradient(135deg, #2980b9, #1c5a87); 
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(52, 152, 219, 0.3);
        }
        
        .download-container { text-align: center; margin: 20px 0; }
        
        .stats-info {
            background: white;
            padding: 20px;
            border-radius: 10px;
            margin: 20px auto;
            width: 90%;
            box-shadow: 0 3px 10px rgba(0,0,0,0.05);
        }
        
        .stats-info p {
            margin: 8px 0;
            font-size: 16px;
        }
        
        .stats-info strong {
            color: #2c3e50;
        }
        
        .no-data {
            text-align: center;
            padding: 40px;
            color: #7f8c8d;
            font-style: italic;
        }
    </style>
</head>
<body>

<nav class="navbar">
  <div class="nav-left"><h2>🌾 DMAS Admin Panel</h2></div>
  <div class="nav-right">
    <a href="admin_dashboard.php">🏠 Dashboard</a>
    <a href="user_management.php">👥 Manage Users</a>
    <a href="order_management.php" >📦 View Orders</a>
    <a href="admin_report.php"class="active">📄 Report</a>
    <a href="worker_registration.php">📝 Worker Registration</a>
    <a href="../logout.php" class="logout">🚪 Logout</a>
  </div>
</nav>

<h2>📊 Generate Monthly Report</h2>

<!-- Month-Year Selection Form -->
<div class="form-box">
    <form method="POST">
        <label for="month">Select Month</label>
        <select name="month" id="month" required>
            <?php
            for ($m = 1; $m <= 12; $m++) {
                $monthText = date("F", mktime(0, 0, 0, $m, 1));
                $sel = ($m == $selectedMonth) ? 'selected' : '';
                echo "<option value='$m' $sel>$monthText</option>";
            }
            ?>
        </select>

        <label for="year">Select Year</label>
        <select name="year" id="year" required>
            <?php
            $currentYear = date('Y');
            for ($y = $currentYear; $y >= $currentYear - 5; $y--) {
                $sel = ($y == $selectedYear) ? 'selected' : '';
                echo "<option value='$y' $sel>$y</option>";
            }
            ?>
        </select>

        <button type="submit">📄 Generate Report</button>
    </form>
</div>

<?php if ($pdfGenerated): ?>
    <!-- Display Summary Stats -->
    <div class="stats-info">
        <h3 style="text-align: center; color: #27ae60;">Report Summary for <?= $monthName . ' ' . $selectedYear ?></h3>
        <p><strong>Total Orders:</strong> <?= $totalOrders ?></p>
        <p><strong>Total Quantity Sold:</strong> <?= $totalQuantity ?></p>
        <p><strong>Total Income:</strong> LKR <?= number_format($totalIncome, 2) ?></p>
        <p><strong>PDF Generated:</strong> <?= $pdfName ?></p>
    </div>

    <!-- PDF Viewer -->
    <iframe src="<?= $pdfName ?>"></iframe>

    <!-- Download Button -->
    <div class="download-container">
        <a href="<?= $pdfName ?>" class="btn" download>⬇️ Download PDF Report</a>
    </div>
<?php elseif ($_SERVER['REQUEST_METHOD'] === 'POST'): ?>
    <div class="no-data">
        <h3>⚠️ No Data Available</h3>
        <p>No orders were found for <?= $monthName . ' ' . $selectedYear ?>.</p>
        <p>Please select a different month or year.</p>
    </div>
<?php endif; ?>

</body>
</html>